name: buildAndDeploy
#监听
on:
  # 提交
  push:
    # 分支
    branches:
      # 主分支
      - master

jobs:
  build:
    # 选择最新的ubuntu系统
    runs-on: ubuntu-latest
    # 步骤
    steps:
      # 将代码拷贝到虚机中
      - name: checkout master
        uses: actions/checkout@master

      - name: buildAndDeploy
        uses: JamesIves/github-pages-deploy-action@master 
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
          BRANCH: gh-pages # 存放产物的分支名称
          FOLDER: dist # 存放build后产物的目录
          BUILD_SCRIPT: npm install && npm run build # 执行的命令
